version: "2"
services:
  expressexam-db:
    container_name: expressexam-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - expressexam-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - expressexam-db
  expressexam:
    container_name: expressexam
    build:
      context: ./
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - expressexam-db
    volumes:
      - "./:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - expressexam
networks:
  inner: {}
volumes:
  expressexam-db-data: {}
